#define szErr_Compile		L"编译错误：文件头长度=0x%X（应该为0x80），请报告此错误。"
#define szErr_OpenFile		L"无法打开%s！"
#define szErr_WriteFile		 "无法写入%s！"

#define szErr_MinusLength	L"第%d行　语法错误，负数长度%d。"
#define szErr_CodeLen		 "第%d行　%s：无法将长度设为%d。"
#define szErr_OprandLen		 "第%d行　%s：非法的操作数长度%d。"
#define szInfo_Period		L"第%d行　.：地址为%04X。"
#define szErr_IllegalOprand	 "第%d行　%s：语法错误，不能作为操作数。"
#define szErr_VoidLabel		L"第%d行　%c：语法错误，空标签。"
#define szErr_At_Addr		L"第%d行　@：无法将地址设为%X。"
#define szErr_Colon_Redefine	 "第%d行　:：无法重新定义标签%s（地址%04X）。"
#define szErr_ReferenceMode	L"第%d行　%c：未定义的参照模式%d，请报告此错误。"
#define szErr_Quotation_LenEx	 "第%d行　\"：字符串%s超出长度%d。"
#define szErr_End_TooMuch	L"第%d行　}:语法错误，结束比开始多。"
#define szErr_Backslash_Unknown	 "第%d行　\\：未知的宏%s。"
#define szErr_Opcode_Unknown	 "第%d行　%s：未知的命令名。"
#define szErr_StrLen		L"第%d行　\\%s：过长的一行。"
#define szErr_TooMuchBegin	L"开始比结束多。"
#define szErr_LabelUndefined	 "标签%s未定义。"
#define szErr_Underflow		L"数据地址低于0x6000。"
#define szErr_BinStart		L"在bin模式中无法从地址%04X开始。"
#define szWarn_Underflow	L"在地址%04X前的数据将被无视。"
#define szWarn_Overflow		L"从地址%04X开始的数据将被无视。"

WCHAR szAppName[]=L"nsfaa";
