#define szErr_Compile		L"Compile error: header lenth=0x%X(expected 0x80), please report this bug."
#define szErr_OpenFile		L"Can't open '%s'!"
#define szErr_WriteFile		 "Can't write '%s'!"

#define szErr_MinusLength	L"Line %d syntax error, minus length %d."
#define szErr_CodeLen		 "Line %d %s: can't set length to %d."
#define szErr_OprandLen		 "Line %d %s: illegal operand length %d."
#define szInfo_Period		L"Line %d .: address is %04X."
#define szErr_IllegalOprand	 "Line %d %s: syntax error, illegal as operand."
#define szErr_VoidLabel		L"Line %d %c: syntax error, void label."
#define szErr_At_Addr		L"Line %d @: can't set address to %X."
#define szErr_Colon_Redefine	 "Line %d :: can't redefine label %s at %04X."
#define szErr_ReferenceMode	L"Line %d %c: undefined reference mode %d, please report this bug."
#define szErr_Quotation_LenEx	 "Line %d \": string %s exceeded length %d."
#define szErr_End_TooMuch	L"Line %d }: syntax error, more end than begin."
#define szErr_Backslash_Unknown	 "Line %d \\: unknown macro %s."
#define szErr_Opcode_Unknown	 "Line %d %s: unknown instruction."
#define szErr_StrLen		L"Line %d \\%s: too long line."
#define szErr_TooMuchBegin	L"More begin than end."
#define szErr_LabelUndefined	 "Label %s undefined."
#define szErr_Underflow		L"Data under 0x6000."
#define szErr_BinStart		L"Can't start with %04X in bin mode."
#define szWarn_Underflow	L"Data before %04X will be ignored."
#define szWarn_Overflow		L"Data from %04X will be ignored."

WCHAR szAppName[]=L"nsfaa";
