#define szErr_Compile		L"コンパイルエラー：ヘッダー長さ=0x%X（0x80となるべき）、このバグをご報告ください。"
#define szErr_OpenFile		L"%sが開きません。"
#define szErr_WriteFile		 "%sに書き込めません。"

#define szErr_MinusLength	L"%d行　文法エラー、マイナスの長さ%dです。"
#define szErr_CodeLen		 "%d行　%s：長さを%dに設定できません。"
#define szErr_OprandLen		 "%d行　%s：不正のオペランド長さ%dです。"
#define szInfo_Period		L"%d行　.：アドレスは%04Xです。"
#define szErr_IllegalOprand	 "%d行　%s：文法エラー、オペランドになりません。"
#define szErr_VoidLabel		L"%d行　%c：文法エラー、空のラベルです。"
#define szErr_At_Addr		L"%d行　@：アドレスを%Xにセットできません。"
#define szErr_Colon_Redefine	 "%d行　:：ラベル%sは再定義できません（アドレス%04X）。"
#define szErr_ReferenceMode	L"%d行　%c：参照モード%dは定義されませんでした。このバグをご報告ください。"
#define szErr_Quotation_LenEx	 "%d行　\"：文字列%sは長さ%dを超えています。"
#define szErr_End_TooMuch	L"%d行　}:文法エラー、終了は開始より多いです。"
#define szErr_Backslash_Unknown	 "%d行　\\：不明なマクロ%sです。"
#define szErr_Opcode_Unknown	 "%d行　%s：不明な命令です。"
#define szErr_StrLen		L"%d行　\\%s：長すぎる行です。"
#define szErr_TooMuchBegin	L"開始は終了より多いです。"
#define szErr_LabelUndefined	 "ラベル%sは定義されませんでした。"
#define szErr_Underflow		L"データのアドレスは0x6000を下回っています。"
#define szErr_BinStart		L"binモードでは%04Xから始めては行けません。"
#define szWarn_Underflow	L"%04Xより前のデータは無視されます。"
#define szWarn_Overflow		L"%04X以降のデータは無視されます。"

WCHAR szAppName[]=L"nsfaa";
